---
title: "Instalacion de R y RStudio"
author: "Priscilla Minotti"
date: "11 de mayo de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(Basado en los materiales de los talleres de Riva Quiroga y Laura Ación)

# R
Descargá R desde https://cran.r-project.org/. Debés elegir la opción que corresponda, según tu sistema operativo. 
Instalá R en tu computadora, tal como lo hacés con cualquier programa.

# RStudio
Una vez que R quedó correctamente instalado, descargá RStudio desde https://www.rstudio.com/products/rstudio/download/. 
Eligí la primera opción, es decir, "RStudio Desktop Open Source License" (gratuita). Instalá luego RStudio en tu computadora, tal como lo haces con cualquier programa.

Aqui hay un paso a paso completo R_Curso_de_Nivelacion/Instalacion_R_RStudio.pdf

IMPORTANTE: Si aparece algún error durante este proceso, lo más probabable es que sea por alguna configuración de tu sistema operativo. En ese caso, la mejor manera de buscar una solución es copiar el error que arroja R, pegarlo en, por ejemplo, Google y ver cómo alguien que se enfrentó a eso antes lo resolvió. Si no lográs solucionarlo, veremos problemas que hayan surgido personalmente durante el transcurso del curso.
